### ISSUE TITLE
Rarbg integration update

### ISSUE THREAD

**Issue by rarbg** [ttlequals0/plex-scripts#1]
Hello
Please upgrade your app to utilize the available api of our site instead of direct hitting it.
You can read the api docs here
https://torrentapi.org/apidocs_v2.txt

**Comment by ttlequals0** [comment]
I was unaware of your site having an api. I will update the script to utilize the apiy

**Comment by rarbg** [comment]
Thanks

**Comment by ttlequals0** [comment]
Is there anyway to get imdb rating via api

**Comment by rarbg** [comment]
Not right now , but ill do it within 24h

**Comment by rarbg** [comment]
Hey @ttlequals0 is it ok if i return the rating in format rating/number of users that rated?

**Comment by ttlequals0** [comment]
I was pulling the IMDB rating from the results page. 
Example. Drama, Family IMDB: 6.6/10

**Comment by rarbg** [comment]
So in what format do you want it then ?

**Comment by ttlequals0** [comment]
rating/number of users that rated.  would work.

**Comment by ttlequals0** [comment]
Do you have any updates on adding rating. I also noticed the api only returns magnet links not true links.  It would be nice to have actual links instead.

**Comment by rarbg** [comment]
Not done yet , ill do it on Monday because im reparsing imdb for the ratings and it will complete Monday.
About the "true links" - you dont need them , just get the HASH from them and then just use any of the following 
{http|https}://torcache.net/torrent/{HASH}.torrent
{http|https}://thetorrent.org/torrent/{HASH}.torrent
{http|https}://btdig.com/torrent/{HASH}.torrent
{http|https}://itorrents.org/torrent/{HASH}.torrent

**Comment by ttlequals0** [comment]
Any updates?

**Comment by ttlequals0** [comment]
Is there any ongoing issues with your api services. I am receiving 500 errors?

**Comment by rarbg** [comment]
@ttlequals0 
No there are no ongoing issues or any issues in the past 24 hours that can cause you to see 500.
Its probably the CF geo ->us connectivity issues and thats why you are seeing those errors.

**Comment by ttlequals0** [comment]
Well you might want to look into it since it has been a week since it has last worked.

**Comment by rarbg** [comment]
@ttlequals0 
There are thousands of people using the API , 10+ apps that utilize it.
Noone else complained and i dont see elevated error count on any counter.
Please be more specific and give me the url + the __exact__ html that you get from the 500 error

**Comment by ttlequals0** [comment]
Its not your site its the cacheing services that are broken.  All of them return 404 for files do you know any that actually work?

**Comment by rarbg** [comment]
@ttlequals0 
For which files exactly ?
Again , be specific.

**Comment by ttlequals0** [comment]
Getting the hash.Torrent files from the caching services since I can't get them directly from your site.

**Comment by rarbg** [comment]
@ttlequals0 
Be specific or i cant help you. This is completely undescriptive of your side.
Provide the urls you are trying to access so i can see why you get the 404.

**Comment by ttlequals0** [comment]
Would it be possible to just provide direct links to torrent files on your site via api?

**Comment by rarbg** [comment]
Thats never going to happen

**Comment by ttlequals0** [comment]
Can you provide a place where the files will be reliably accessible?

**Comment by rarbg** [comment]
I already did.
{http|https}://torcache.net/torrent/{HASH}.torrent
{http|https}://thetorrent.org/torrent/{HASH}.torrent
{http|https}://btdig.com/torrent/{HASH}.torrent
{http|https}://itorrents.org/torrent/{HASH}.torrent

**Comment by ttlequals0** [comment]
These don't work nothing but server errors and invalid files.  If you look inside the files it's either html 404 errors or a bunch of random garbage.

**Comment by rarbg** [comment]
Im sorry i dont think you are suitable or even capable of handling torrents so im going to close this ticket
